apiVersion: v1
kind: Namespace
metadata:
  name: microservices
  labels:
    name: microservices
    app.kubernetes.io/name: microservices
    app.kubernetes.io/instance: devsecops
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: devsecops-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/instance: devsecops
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: devsecops-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    name: security
    app.kubernetes.io/name: security
    app.kubernetes.io/instance: devsecops
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: devsecops-platform
