apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: microservices
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/instance: devsecops
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: microservices
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: devsecops
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microservices
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/instance: devsecops
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: microservices
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: auth
    app.kubernetes.io/instance: devsecops
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: microservices
  labels:
    app.kubernetes.io/name: database-service
    app.kubernetes.io/instance: devsecops
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: microservices
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app.kubernetes.io/name: database
    app.kubernetes.io/instance: devsecops
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: microservices
  labels:
    app.kubernetes.io/name: gateway-service
    app.kubernetes.io/instance: devsecops
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: microservices
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: devsecops
