name: Docker Image CI

on:
  push:
    branches: [ "dependabot/maven/customer-service/mysql-mysql-connector-java-8.0.28" ]
  pull_request:
    branches: [ "dependabot/maven/customer-service/mysql-mysql-connector-java-8.0.28" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
